### ISSUE TITLE
Support for Pale

### ISSUE THREAD

**Issue by siteuser42** [nicohman/rust-wildbow-scraper#15]
Thanks for the scraper and all the work involved! If possible, I'd like to request support for the new serial, Pale. 

Alternatively/additionally, the older scraper (https://github.com/mikeappell/worm-scraper), allowed for a workaround for new urls with the -s option,
"worm-scraper -s https://palewebserial.wordpress.com/2020/05/05/blood-run-cold-0-0/ download convert scaffold zip"

This works, but is not a perfect solution because all the metadata/cover still defaults to Worm. Support for an analogous feature could be useful in the future.

**Comment by nicohman** [comment]
Pushed an update that adds support for pale. Should work, although I did make the 'Next Chapter' link filter broader because the format is different for pale, so there might be some issues with other serials. Basic testing looks good though. Truncated the description because it's really long for this one, but not super happy with it.

**Comment by siteuser42** [comment]
Awesome, thanks!

**Comment by samuelmayerhofer** [comment]
How, exactly, do I scrape pale? There's no documentation for it.
