### ISSUE TITLE
Fails on Ward

### ISSUE THREAD

**Issue by C0rn3j** [nicohman/rust-wildbow-scraper#8]
```
Now downloading Ward
Downloaded Daybreak - 1.1
thread 'reductor' panicked at 'called `Result::unwrap()` on an `Err` value: Inner { kind: Hyper(Error { kind: Connect, cause: Some(Custom { kind: Other, error: StringError("failed to lookup address information: Name or service not known") }) }), url: Some("https://http//www.parahumans.net/2017/11/14/daybreak-1-2/") }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:997:5
```
For some reason the scrapped is trying to access
`https://http//www.parahumans.net/2017/11/14/daybreak-1-2/`

Instead of
`https://www.parahumans.net/2017/11/14/daybreak-1-2/`

I simply ran `/root/.cargo/bin/rust-wildbow-scraper -a -y`

**Comment by nicohman** [comment]
It looks like the link format changed for some reason recently, using http instead of https or no specifier. I made sure that it now checks if the link already includes https or http and it should work now. Thanks for letting me know! I'm going to close this issue but please reopen it if it still doesn't work for you.
